export const skills = [
  'JavaScript',
  'TypeScript',
  'HTML5',
  'CSS3',
  'React',
  'Next.js',
  'Node.js',
  'Express',
  'GraphQL',
  'REST APIs',
  'MongoDB',
  'PostgreSQL',
  'MySQL',
  'Git',
  'GitHub',
  'CI/CD',
  'Jest',
  'Mocha',
  'Chai',
  'Tailwind CSS',
  'Redux',
  'AWS',
  'Firebase',
  'OAuth',
  'JWT Authentication',
  'SASS',
  'Socket.IO',
  'Microservices Architecture',
];

export const links = [
  { name: 'Home', link: '#home' },
  { name: 'About', link: '#about' },
  { name: 'Projects', link: '#projects' },
  { name: 'Skills', link: '#skills' },
  { name: 'Experience', link: '#experience' },
  { name: 'Contact', link: '#contact' },
] as const;
